TESTS.push(
{id:"TC11",title:"Kéo thanh trượt tới 3.5",route:"/horizontal_slider",spec:"horizontalSlider.spec.ts",test:"change range slider value",group:"Thao tác form",app:"Thanh trượt từ 0 đến 5, mỗi bước 0.5, điều khiển bằng phím mũi tên.",steps:["Mở trình duyệt, vào trang /horizontal_slider","Nhấn ArrowRight nhiều lần cho tới khi giá trị bằng 3.5","Kiểm tra giá trị bằng 3.5"],why:"Vòng lặp đọc giá trị sau mỗi lần nhấn phím, mô phỏng đúng thao tác bàn phím của người dùng."},
{id:"TC12",title:"Nhấn phím và xem kết quả",route:"/key_presses",spec:"keyPresses.spec.ts",test:"verify key press result",group:"Thao tác form",app:"Mỗi phím được nhấn sẽ hiển thị tên phím đó.",steps:["Mở trình duyệt, vào trang /key_presses","Bấm vào ô nhập, nhấn Tab, kiểm tra You entered: TAB","Nhấn phím a, kiểm tra You entered: A"],why:"Phải bấm vào ô để lấy tiêu điểm trước khi nhấn phím, nếu không kết quả sẽ trống."},
{id:"TC13",title:"Nhập số vào ô number",route:"/inputs",spec:"inputs.spec.ts",test:"verify number input accepts value",group:"Thao tác form",app:"Ô kiểu số nhận giá trị số, phím mũi tên lên tăng thêm 1.",steps:["Mở trình duyệt, vào trang /inputs","Nhập 123, kiểm tra giá trị là 123","Nhấn ArrowUp, kiểm tra giá trị là 124"],why:"Kết hợp fill và press trên cùng một ô nhập để phủ cả nhập tay lẫn nút tăng."},
{id:"TC14.1",title:"Tải một tệp về",route:"/download",spec:"download.spec.ts",test:"download a file",group:"Tải tệp/tab mới",app:"Bấm liên kết sẽ tải tệp về máy.",steps:["Mở trình duyệt, vào trang /download","Bấm tệp cần tải, lưu vào thư mục downloads/","Kiểm tra tệp đã tồn tại"],why:"Phải chờ sự kiện download CÙNG LÚC với cú bấm trong Promise.all vì sự kiện xảy ra ngay sau đó, chờ sau sẽ bị trượt."},
{id:"TC14.2",title:"Tải nhiều tệp",route:"/download",spec:"download.spec.ts",test:"download multiple files",group:"Tải tệp/tab mới",app:"Tải nhiều tệp liên tiếp.",steps:["Mở trình duyệt, vào trang /download","Tải t1.txt và text.txt vào downloads/","Kiểm tra cả hai tệp tồn tại"],why:"Lặp lại mẫu Promise.all cho từng tệp để không bỏ sót sự kiện tải nào."},
{id:"TC14.3",title:"Tải tệp cần đăng nhập",route:"/download_secure",spec:"secureDownload.spec.ts",test:"download a secure file",group:"Xác thực",app:"Route này đòi tài khoản admin, danh sách tệp thay đổi theo thời gian.",steps:["Đăng nhập admin/admin","Vào trang /download_secure","Bấm tệp đầu tiên, lưu về downloads/","Kiểm tra tệp đã tồn tại"],why:"Không đăng nhập sẽ bị từ chối; bấm tệp đầu tiên thay vì tên cố định vì danh sách tệp là động."},
{id:"TC14.4",title:"Tải tệp lên",route:"/upload",spec:"uploadFile.spec.ts",test:"upload a file",group:"Thao tác form",app:"Chọn tệp trên máy rồi bấm Upload.",steps:["Mở trình duyệt, vào trang /upload","Chọn tệp uploads/resume.txt","Bấm Upload, kiểm tra hiện tên resume.txt"],why:"setInputFiles tránh hộp thoại chọn tệp của hệ điều hành nên chạy ổn định trên CI."},
{id:"TC15.1",title:"Xác thực cơ bản Basic Auth",route:"/basic_auth",spec:"basicAuth.spec.ts",test:"login successfully with valid credential",group:"Xác thực",app:"Xác thực cơ bản chấp nhận tài khoản admin.",steps:["Mở trang kèm tài khoản admin trong địa chỉ","Kiểm tra hiện tiêu đề Basic Auth"],why:"Basic Auth cho phép nhúng tài khoản vào địa chỉ URL, cách nhanh nhất cho case đơn giản."},
{id:"TC15.2",title:"Xác thực Digest Auth",route:"/digest_auth",spec:"digestAuth.spec.ts",test:"login successfully with digest auth",group:"Xác thực",app:"Xác thực Digest cần hỏi-đáp thử thách nên không nhúng URL được.",steps:["Cấu hình tài khoản admin/admin cho phiên kiểm thử","Vào trang /digest_auth","Kiểm tra dòng Congratulations..."],why:"Dùng httpCredentials để trình duyệt tự trả lời thử thách 401, cách duy nhất ổn định cho Digest."},
{id:"TC16",title:"Kiểm tra ảnh hỏng",route:"/broken_images",spec:"brokenImage.spec.ts",test:"verify broken image",group:"Quan sát trình duyệt",app:"Vài ảnh trên trang bị hỏng (máy chủ trả 404).",steps:["Mở trình duyệt, vào trang /broken_images","Với mỗi thẻ img: lấy src và gọi thử","Kiểm tra mã trạng thái bằng 200"],why:"Dùng API gọi thử thay vì nhìn bằng mắt mới đúng bản chất ảnh hỏng; expect.soft để thấy hết các ảnh lỗi."}
);
