TESTS.push(
{id:"TC22.2",title:"Nội dung tĩnh giữ ảnh đại diện",route:"/dynamic_content?static",spec:"dynamicContent.spec.ts",test:"verify static content link keeps avatar images",group:"Chờ động",app:"Bản tĩnh giữ nguyên ảnh đại diện.",steps:["Mở trang kèm ?with_content=static","Kiểm tra tiêu đề và ảnh đại diện còn đủ"],why:"Tham số truy vấn static làm đổi hành vi của trang."},
{id:"TC22.3",title:"Menu lúc ẩn lúc hiện",route:"/disappearing_elements",spec:"disappearingElements.spec.ts",test:"verify disappearing elements menu",group:"Locator cơ bản",app:"Mục Gallery trong menu lúc ẩn lúc hiện.",steps:["Kiểm tra Home và About đang hiện","Tải lại trang, kiểm tra còn ít nhất 4 mục"],why:"Tải lại để gặp trạng thái menu khác; dùng lớn-hơn-hoặc-bằng vì Gallery có thể mất."},
{id:"TC23.1",title:"Nội dung kiểm thử A/B",route:"/abtest",spec:"abTest.spec.ts",test:"verify ab test content",group:"Locator cơ bản",app:"Trang kiểm thử A/B đơn giản.",steps:["Mở trang /abtest","Kiểm tra tiêu đề chứa A/B Test và đoạn văn không rỗng"],why:"Dùng chứa-chuỗi thay vì bằng-chuỗi vì tiêu đề có nhiều biến thể."},
{id:"TC23.2",title:"Bảng DOM khó",route:"/challenging_dom",spec:"challengingDom.spec.ts",test:"verify challenging dom table",group:"Quan sát trình duyệt",app:"Mỗi lần tải, id của các nút đều đổi hết.",steps:["Kiểm tra bảng có 10 hàng","Bấm nút đầu tiên, kiểm tra id đã đổi"],why:"Tận dụng đặc tính id ngẫu nhiên để kiểm tra trang đã vẽ lại."},
{id:"TC23.3",title:"Bảng lớn 50 hàng",route:"/large",spec:"largeDom.spec.ts",test:"verify large dom table rows",group:"Quan sát trình duyệt",app:"Bảng lớn 50 hàng để thử chiến lược tìm phần tử.",steps:["Mở trang /large","Kiểm tra bảng có 50 hàng, hàng đầu chứa 1.1"],why:"toHaveCount tự chờ đến khi trang vẽ xong toàn bộ bảng lớn."},
{id:"TC23.4",title:"Các khối div lồng nhau",route:"/large",spec:"largeDom.spec.ts",test:"verify sibling divs structure",group:"Quan sát trình duyệt",app:"Cấu trúc div lồng nhau rất sâu.",steps:["Kiểm tra khối sibling-1.1 đang hiện","Kiểm tra dòng No siblings"],why:"Phải thoát ký tự chấm trong id khi viết selector CSS."},
{id:"TC24.1",title:"Thêm và xóa phần tử",route:"/add_remove_elements/",spec:"addRemoveElements.spec.ts",test:"add and remove elements",group:"Locator cơ bản",app:"Nút Add Element sinh ra các nút Delete.",steps:["Bấm Add hai lần, kiểm tra có 2 nút Delete","Bấm nút Delete đầu tiên, kiểm tra còn 1 nút"],why:"toHaveCount là kiểm tra chuẩn cho danh sách thay đổi động."},
{id:"TC24.2",title:"Liên kết chuyển hướng",route:"/redirector",spec:"redirector.spec.ts",test:"verify redirect to status code page",group:"Locator cơ bản",app:"Liên kết here sẽ chuyển sang trang mã trạng thái.",steps:["Bấm liên kết #redirect","Kiểm tra URL chứa /status_codes và hiện tiêu đề"],why:"Dùng id thay vì chữ here vì chữ này trùng ở nhiều nơi."},
{id:"TC24.3",title:"Thông báo sau thao tác",route:"/notification_message",spec:"notificationMessage.spec.ts",test:"verify notification message shows after click",group:"Chờ động",app:"Thông báo ngẫu nhiên, đôi khi trang vẽ trống.",steps:["Vào trang hiển thị thông báo","Bấm Click here tối đa 5 lần","Kiểm tra dòng Action successful hoặc unsuccessful"],why:"Thử lại vì máy chủ trả ngẫu nhiên và có thể trả khung trống."},
{id:"TC24.4a",title:"Nội dung dịch chuyển - menu",route:"/shifting_content/menu",spec:"shiftingContent.spec.ts",test:"verify menu items shift on reload",group:"Locator cơ bản",app:"Thứ tự menu đổi mỗi lần tải.",steps:["Kiểm tra menu có 5 mục","Tải lại, vẫn có 5 mục"],why:"Chỉ kiểm tra số lượng, không kiểm tra thứ tự vì thứ tự ngẫu nhiên."}
);
