TESTS.push(
{id:"TC17.1",title:"Cửa sổ quảng cáo tự hiện",route:"/entry_ad",spec:"adPopup.spec.ts",test:"handle entry ad popup",group:"Chuột",app:"Cửa sổ quảng cáo hiện ra sau vài giây.",steps:["Mở trình duyệt, vào trang /entry_ad","Khi cửa sổ THIS IS A MODAL WINDOW hiện, bấm đóng","Kiểm tra tiêu đề Entry Ad vẫn hiện"],why:"addLocatorHandler tự xử lý cửa sổ bất cứ khi nào nó xuất hiện, kèm bỏ qua trình duyệt webkit còn lỗi."},
{id:"TC17.2",title:"Cửa sổ khi di chuột ra ngoài",route:"/exit_intent",spec:"exitIntent.spec.ts",test:"verify exit intent modal shows on mouse out",group:"Chuột",app:"Rê chuột ra mép trên trình duyệt sẽ bật cửa sổ.",steps:["Mở trình duyệt, vào trang /exit_intent","Di chuột ra ngoài mép trên","Kiểm tra cửa sổ hiện, đóng lại, kiểm tra đã ẩn"],why:"Trang bắt sự kiện chuột rời khung nhìn nên phải di chuyển hai điểm có bước đệm; hover đơn thuần không kích hoạt."},
{id:"TC18.1",title:"Cuộn vô hạn tải thêm",route:"/infinite_scroll",spec:"infinityScroll.spec.ts",test:"verify infinity scroll down",group:"Chuột",app:"Cuộn xuống sẽ tải thêm nội dung.",steps:["Mở trình duyệt, vào trang /infinite_scroll","Cuộn chuột xuống nhiều lần"],why:"mouse.wheel mô phỏng thao tác cuộn thật thay vì gọi hàm cuộn trực tiếp."},
{id:"TC18.2",title:"Menu nổi khi cuộn trang",route:"/floating_menu",spec:"floatingMenu.spec.ts",test:"verify floating menu stays visible on scroll",group:"Chuột",app:"Thanh menu luôn nổi ngay cả khi cuộn trang.",steps:["Kiểm tra menu Home đang hiện","Cuộn xuống 2000px, menu vẫn hiện","Bấm News, kiểm tra URL có #news"],why:"Kiểm tra tính bám dính: sau khi cuộn menu vẫn bấm được và điều hướng đúng."},
{id:"TC19",title:"Mở cửa sổ mới",route:"/windows",spec:"multipleWindows.spec.ts",test:"verify new window opens with text",group:"Tải tệp/tab mới",app:"Bấm Click Here sẽ mở một thẻ mới.",steps:["Mở trình duyệt, vào trang /windows","Bấm Click Here","Kiểm tra thẻ mới hiện New Window, thẻ cũ vẫn nguyên"],why:"Tương tự tải tệp: chờ sự kiện popup cùng lúc với cú bấm để không trượt sự kiện mở thẻ."},
{id:"TC20.1",title:"Xóa rồi thêm lại checkbox",route:"/dynamic_controls",spec:"dynamicControls.spec.ts",test:"remove and add checkbox",group:"Chờ động",app:"Nút Remove/Add xử lý qua AJAX mất vài giây.",steps:["Mở trình duyệt, vào trang /dynamic_controls","Bấm Remove, kiểm tra dòng It's gone! và ô đã ẩn","Bấm Add, kiểm tra dòng It's back! và ô hiện lại"],why:"Tăng thời gian chờ lên 10 giây vì AJAX chậm; dùng dòng thông báo làm tín hiệu đồng bộ."},
{id:"TC20.2",title:"Bật/tắt ô nhập liệu",route:"/dynamic_controls",spec:"dynamicControls.spec.ts",test:"enable and disable input",group:"Chờ động",app:"Nút Enable/Disable ô nhập tương tự.",steps:["Kiểm tra ô đang tắt","Bấm Enable, kiểm tra đã bật và nhập được hello","Bấm Disable, kiểm tra đã tắt"],why:"Kiểm tra đầy đủ vòng đời tắt rồi bật rồi tắt của ô nhập liệu."},
{id:"TC21.1",title:"Tải nội dung ẩn - ví dụ 1",route:"/dynamic_loading/1",spec:"dynamicLoading.spec.ts",test:"verify hidden element loads after start",group:"Chờ động",app:"Dòng Hello World! bị ẩn, hiện ra sau khi bấm Start.",steps:["Mở trang /dynamic_loading/1","Kiểm tra vùng kết quả đang ẩn","Bấm Start, kiểm tra hiện Hello World! trong 15 giây"],why:"Kiểm tra trạng thái ẩn trước để chắc điều kiện ban đầu; chờ 15 giây cho tác vụ chậm."},
{id:"TC21.2",title:"Tải nội dung vẽ sau - ví dụ 2",route:"/dynamic_loading/2",spec:"dynamicLoading.spec.ts",test:"verify rendered element loads after start",group:"Chờ động",app:"Tương tự nhưng phần tử được vẽ ra sau.",steps:["Mở trang /dynamic_loading/2","Kiểm tra đang ẩn, bấm Start","Kiểm tra hiện Hello World! trong 15 giây"],why:"Giữ hai test riêng vì cơ chế hiển thị khác nhau dù kết quả giống nhau."},
{id:"TC22.1",title:"Nội dung đổi sau tải lại",route:"/dynamic_content",spec:"dynamicContent.spec.ts",test:"verify dynamic content changes on reload",group:"Chờ động",app:"Nội dung thay đổi ngẫu nhiên mỗi lần tải lại.",steps:["Mở trình duyệt, vào trang /dynamic_content","Đọc nội dung, tải lại trang","Kiểm tra vẫn có dữ liệu"],why:"Không kiểm tra chữ cụ thể vì nội dung ngẫu nhiên, chỉ kiểm tra cấu trúc còn đầy đủ."}
);
