TESTS.push(
{id:"TC06.1",title:"Nội dung các frame lồng nhau",route:"/nested_frames",spec:"frame.spec.ts",test:"verify nested frames content",group:"Frame",app:"Trang dùng frameset hai tầng: khung trên chia trái/giữa/phải, khung dưới riêng.",steps:["Mở trình duyệt, vào trang /nested_frames","Kiểm tra khung trái hiện LEFT","Kiểm tra khung giữa MIDDLE, khung phải RIGHT, khung dưới BOTTOM"],why:"frameLocator lồng nhau mô tả đúng cây frame thật, tự động chờ frame tải xong nên không cần xử lý thủ công."},
{id:"TC06.2",title:"Trình soạn thảo trong iframe",route:"/iframe",spec:"iframe.spec.ts",test:"verify tinymce editor content",group:"Frame",app:"Trình soạn thảo TinyMCE nằm trong một iframe duy nhất.",steps:["Mở trình duyệt, vào trang /iframe","Kiểm tra khung soạn thảo có dòng Your content goes here."],why:"Dùng frameLocator theo id của iframe, ngắn gọn và chịu được tải lệch giữa các khung."},
{id:"TC06.3",title:"Trình soạn thảo WYSIWYG",route:"/tinymce",spec:"wysiwygEditor.spec.ts",test:"verify editor has default content",group:"Frame",app:"Bản sao của trang iframe, cùng một trình soạn thảo.",steps:["Mở trình duyệt, vào trang /tinymce","Kiểm tra khung soạn thảo có nội dung mặc định"],why:"Giữ hai file riêng để bao phủ đủ cả hai route /iframe và /tinymce."},
{id:"TC07.1",title:"Hộp thoại cảnh báo JS",route:"/javascript_alerts",spec:"jsAlert.spec.ts",test:"js alert",group:"Hộp thoại",app:"Nút bấm kích hoạt hộp cảnh báo của trình duyệt, bấm OK thì báo thành công.",steps:["Mở trình duyệt, vào trang /javascript_alerts","Bấm Click for JS Alert, chấp nhận hộp thoại","Kiểm tra dòng You successfully clicked an alert"],why:"Phải đăng ký xử lý hộp thoại TRƯỚC khi bấm, nếu không Playwright sẽ tự đóng và kiểm tra sai. Đây là mẫu hay lỗi nhất."},
{id:"TC07.2",title:"Hộp xác nhận JS - Cancel",route:"/javascript_alerts",spec:"jsAlert.spec.ts",test:"js confirm =>cancel",group:"Hộp thoại",app:"Hộp xác nhận có hai nhánh OK và Cancel.",steps:["Bấm Click for JS Confirm, chọn Cancel","Kiểm tra dòng You clicked: Cancel"],why:"dismiss() mô phỏng thao tác bấm Cancel của người dùng."},
{id:"TC07.3",title:"Hộp xác nhận JS - OK",route:"/javascript_alerts",spec:"jsAlert.spec.ts",test:"js confirm =>OK",group:"Hộp thoại",app:"Nhánh còn lại của hộp xác nhận.",steps:["Bấm Click for JS Confirm, chọn OK","Kiểm tra dòng You clicked: OK"],why:"accept() mô phỏng thao tác bấm OK."},
{id:"TC07.4",title:"Hộp nhập liệu JS",route:"/javascript_alerts",spec:"jsAlert.spec.ts",test:"js prompt",group:"Hộp thoại",app:"Hộp nhập liệu cho phép gõ chữ.",steps:["Bấm Click for JS Prompt, nhập Hello World","Kiểm tra dòng You entered: Hello World"],why:"accept kèm chuỗi ký tự để truyền nội dung vào hộp nhập liệu."},
{id:"TC08",title:"Di chuột hiện tên người dùng",route:"/hovers",spec:"hover.spec.ts",test:"hover test",group:"Chuột",app:"Phải di chuột lên ảnh đại diện thì tên người dùng mới hiện ra.",steps:["Mở trình duyệt, vào trang /hovers","Di chuột lên ảnh người dùng thứ nhất","Kiểm tra hiện dòng name: user1"],why:".hover() kích hoạt trạng thái CSS :hover; nth(0) chọn đúng ảnh đầu tiên."},
{id:"TC09",title:"Bấm chuột phải mở menu ngữ cảnh",route:"/context_menu",spec:"contextMenu.spec.ts",test:"right click context menu",group:"Hộp thoại",app:"Bấm chuột phải vào ô vuông sẽ bật hộp cảnh báo.",steps:["Mở trình duyệt, vào trang /context_menu","Bấm chuột phải vào vùng hot-spot","Kiểm tra cảnh báo You selected a context menu rồi đóng"],why:"Click với nút phải mô phỏng đúng sự kiện menu ngữ cảnh thật."},
{id:"TC10",title:"Kéo và thả cột",route:"/drag_and_drop",spec:"dragDrop.spec.ts",test:"drag and drop",group:"Chuột",app:"Kéo cột A sang cột B thì nội dung hai cột hoán đổi.",steps:["Mở trình duyệt, vào trang /drag_and_drop","Kiểm tra cột A đang là A","Kéo #column-a sang #column-b, kiểm tra cột A thành B"],why:"dragTo bắn đúng chuỗi sự kiện chuột của kéo-thả HTML5; kiểm tra chữ sau khi kéo để chắc DOM đã đổi."}
);
