TESTS.push(
{id:"TC01.1",title:"Đăng nhập thành công với tài khoản hợp lệ",route:"/login",spec:"login.spec.ts",test:"login success with valid credentials",group:"Locator cơ bản",app:"Form đăng nhập chuẩn: nhập đúng tài khoản thì vào được vùng Secure Area.",steps:["Mở trình duyệt, vào trang /login","Nhập Username là tomsmith, Password là SuperSecretPassword!","Bấm nút Login","Kiểm tra: URL chuyển sang /secure và hiện tiêu đề Secure Area"],why:"Dùng getByRole vì giống cách người dùng nhìn thấy ô nhập và nút bấm, ít gãy khi đổi class hay id. expect toHaveURL có tự động chờ lại trong 5 giây."},
{id:"TC01.2",title:"Đăng nhập với mật khẩu sai",route:"/login",spec:"login.spec.ts",test:"login success with invalid password",group:"Locator cơ bản",app:"Nhập sai mật khẩu phải hiện thông báo lỗi rõ ràng, không được vào trong.",steps:["Mở trình duyệt, vào trang /login","Nhập Username tomsmith, Password thiếu dấu chấm than","Bấm nút Login","Kiểm tra: hiện dòng Your password is invalid!"],why:"Phủ nhánh sai mật khẩu để đủ bộ ba trường hợp: đúng, sai mật khẩu, sai tài khoản."},
{id:"TC01.3",title:"Đăng nhập với tên tài khoản sai",route:"/login",spec:"login.spec.ts",test:"login success with invalid username",group:"Locator cơ bản",app:"Nhập sai tên tài khoản cũng phải báo lỗi tương ứng.",steps:["Mở trình duyệt, vào trang /login","Nhập Username tomsmith! (thừa dấu chấm than)","Bấm nút Login","Kiểm tra: hiện dòng Your username is invalid!"],why:"Hoàn thiện bộ kiểm thử form đăng nhập, mỗi loại lỗi có thông điệp riêng."},
{id:"TC02.1",title:"Tích chọn checkbox",route:"/checkboxes",spec:"checkboxes.spec.ts",test:"verify check success",group:"Thao tác form",app:"Trang có hai ô checkbox với trạng thái ban đầu khác nhau.",steps:["Mở trình duyệt, vào trang /checkboxes","Tích vào checkbox 1, kiểm tra đã được chọn","Tích vào checkbox 2, kiểm tra đã được chọn"],why:"Dùng .check() thay vì click để đảm bảo đúng ngữ nghĩa checkbox, Playwright tự cuộn trang và chờ ô sẵn sàng."},
{id:"TC02.2",title:"Bỏ chọn checkbox",route:"/checkboxes",spec:"checkboxes.spec.ts",test:"verify uncheck success",group:"Thao tác form",app:"Chiều ngược lại: bỏ chọn cả hai ô.",steps:["Mở trình duyệt, vào trang /checkboxes","Bỏ chọn checkbox 1, kiểm tra chưa được chọn","Bỏ chọn checkbox 2, kiểm tra chưa được chọn"],why:".uncheck() kết hợp với not.toBeChecked() phủ cả hai chiều chọn và bỏ chọn."},
{id:"TC03.1",title:"Chọn một lựa chọn trong dropdown",route:"/dropdown",spec:"dropdown.spec.ts",test:"verify select a option success",group:"Thao tác form",app:"Dropdown đơn: chọn Option 1 thì giá trị phải bằng 1.",steps:["Mở trình duyệt, vào trang /dropdown","Chọn Option 1","Kiểm tra giá trị bằng 1, rồi bỏ chọn"],why:"selectOption tác động ở tầng giao thức nên ổn định hơn việc bấm từng option. Xóa chọn cuối test để trạng thái sạch."},
{id:"TC03.2",title:"Chọn nhiều lựa chọn",route:"trang demo",spec:"dropdown.spec.ts",test:"verify selecting multiple options success",group:"Thao tác form",app:"Trang the-internet không có dropdown nhiều lựa chọn nên dùng trang demo phụ.",steps:["Mở trang dropdown demo","Chọn Java và Go trong dropdown nhiều lựa chọn","Kiểm tra giá trị là java, go"],why:"Truyền mảng vào selectOption để chọn nhiều giá trị cùng lúc, toHaveValues kiểm tra đồng thời."},
{id:"TC04",title:"Bấm các liên kết mã trạng thái",route:"/status_codes",spec:"links.spec.ts",test:"verify hyperlink success",group:"Locator cơ bản",app:"Bốn liên kết 200/301/404/500 dẫn tới trang tương ứng, mỗi trang có link here để quay lại.",steps:["Mở trình duyệt, vào trang /status_codes","Bấm 200, kiểm tra URL /200, quay lại","Lặp lại với 301, 404 và 500"],why:"Mẫu kiểm thử điều hướng kết hợp toHaveURL; dùng goBack hoặc link here để tránh phải tải lại trang."},
{id:"TC05.1",title:"Tìm người có khoản nợ lớn nhất",route:"/tables",spec:"table.spec.ts",test:"verify max due person name",group:"Quan sát trình duyệt",app:"Bảng có cột Due ($). Người nợ nhiều nhất là Jason Doe.",steps:["Mở trình duyệt, vào trang /tables","Đọc bảng 2: họ tên và khoản nợ từng người","Kiểm tra người nợ nhiều nhất là Jason Doe"],why:"Chuyển dữ liệu bảng thành kiểu Person rồi dùng Math.max và filter; beforeEach và test.step giúp báo cáo rõ từng bước."},
{id:"TC05.2",title:"Tìm người có khoản nợ nhỏ nhất",route:"/tables",spec:"table.spec.ts",test:"verify min due person name",group:"Quan sát trình duyệt",app:"Có hai người cùng mức nợ thấp nhất.",steps:["Mở trình duyệt, vào trang /tables","Đọc bảng 2: họ tên và khoản nợ","Kiểm tra hai người nợ ít nhất là John Smith và Tim Conway"],why:"Tương tự case trên, bao phủ cả trường hợp nhiều người đồng hạng."}
);
