TESTS.push(
{id:"TC24.4b",title:"Nội dung dịch chuyển - ảnh",route:"/shifting_content/image",spec:"shiftingContent.spec.ts",test:"verify image shifts on reload",group:"Locator cơ bản",app:"Ảnh lệch vài điểm ảnh mỗi lần tải.",steps:["Kiểm tra ảnh shift đang hiện và src là /img/avatar.jpg"],why:"Kiểm tra nguồn ảnh thay vì vị trí điểm ảnh vì vị trí khó kiểm tra."},
{id:"TC24.4c",title:"Nội dung dịch chuyển - danh sách",route:"/shifting_content/list",spec:"shiftingContent.spec.ts",test:"verify list shifts on reload",group:"Locator cơ bản",app:"Danh sách đổi cấu trúc.",steps:["Kiểm tra nội dung đang hiện và số hàng lớn hơn 0"],why:"Kiểm tra cấu trúc còn tồn tại thay vì nội dung cụ thể."},
{id:"TC25.1",title:"Quên mật khẩu báo lỗi máy chủ",route:"/forgot_password",spec:"forgotPassword.spec.ts",test:"verify forgot password form submits",group:"Locator cơ bản",app:"Máy chủ đang lỗi 500 thật khi gửi form.",steps:["Nhập test@example.com rồi gửi","Kiểm tra hiện Internal Server Error"],why:"Ghi nhận đúng hành vi thật của máy chủ, không giả vờ kiểm thử qua."},
{id:"TC25.2",title:"Lỗi chính tả ngẫu nhiên",route:"/typos",spec:"typos.spec.ts",test:"verify typo text content",group:"Locator cơ bản",app:"Đoạn văn đôi khi dính lỗi chính tả.",steps:["Mở trang /typos","Kiểm tra đoạn văn khớp mẫu Sometimes you'll see a typo"],why:"Biểu thức chính quy chịu được cả hai biến thể có và không có lỗi."},
{id:"TC25.3",title:"Lỗi JavaScript khi tải trang",route:"/javascript_error",spec:"javascriptError.spec.ts",test:"verify console error on page load",group:"Quan sát trình duyệt",app:"Trang tự ném lỗi JavaScript ngay khi tải.",steps:["Lắng nghe lỗi trang trước khi vào","Kiểm tra tiêu đề lỗi","Kiểm tra lỗi chứa Cannot read properties"],why:"Sự kiện pageerror bắt ngoại lệ của trang (khác với console), phải lắng nghe trước khi vào trang mới hứng được lỗi lúc tải."},
{id:"TC25.4",title:"Tài nguyên tải chậm",route:"/slow",spec:"slowResources.spec.ts",test:"verify slow resource page loads",group:"Chờ động",app:"Tài nguyên ngoài chậm hơn 30 giây, máy chủ hay trả 503.",steps:["Chờ phản hồi slow_external trong 45 giây","Kiểm tra tiêu đề và mã trạng thái 200 hoặc 503"],why:"Chờ phản hồi mạng thay vì ngủ cứng; chấp nhận 503 vì đó là hành vi thật của máy chủ miễn phí."},
{id:"TC26.1",title:"Menu jQuery nhiều cấp",route:"/jqueryui/menu",spec:"jqueryMenu.spec.ts",test:"verify jquery ui menu navigation",group:"Chuột",app:"Menu hai cấp Enabled rồi Downloads.",steps:["Di chuột lên Enabled rồi Downloads","Kiểm tra hiện liên kết menu.pdf và menu.csv"],why:"Di chuột tuần tự để mở từng cấp menu con rồi mới kiểm tra liên kết tải xuống."},
{id:"TC26.2",title:"Chữ trong Shadow DOM",route:"/shadowdom",spec:"shadowDom.spec.ts",test:"verify shadow dom text",group:"Quan sát trình duyệt",app:"Dòng chữ nằm trong shadow root.",steps:["Mở trang /shadowdom","Kiểm tra dòng chữ đang hiện"],why:"Playwright xuyên qua shadow DOM nên tìm bằng chữ vẫn thấy."},
{id:"TC26.3",title:"Vị trí địa lý",route:"/geolocation",spec:"geolocation.spec.ts",test:"verify geolocation shows coordinates",group:"Xác thực",app:"Trang đọc tọa độ của trình duyệt.",steps:["Tạo phiên mới với tọa độ TP.HCM","Bấm Where am I?","Kiểm tra vĩ độ và kinh độ"],why:"Phải cấp quyền vị trí TRƯỚC khi tải trang vì trang gọi lấy vị trí ngay khi bấm, cấp sau sẽ bị từ chối."}
);
